### ISSUE TITLE
Usage documentation?

### ISSUE THREAD

**Issue by blak3mill3r** [tarleb/evil-rebellion#5]
This looks fantastic, but ... how is one meant to make use of this?

I really want evil bindings for magit. I tried a few ways of making use of evil-rebellion but couldn't get it to work. My first idea was installing it with Cask and `require`ing it in init.el. (I'm an emacs noob btw)

Once I put the `require` somewhere where both evil and magit stuff had been defined, I got around the error (invalid function evil-define-key) and emacs started ... but to my dismay I still had default crap bindings in magit-diff.

It would be wonderful to have some simple guidance for noobs like me in the README indicating how to use evil-rebellion.

**Comment by ajoslin** [comment]
Just stumbled on your issue while looking at magit evil.

`(load-file "~/.emacs.d/evil-magit-rebellion.el")` is the simplest way.

However, I've actually decided to just disable evil mode while in magit, because I'll have an even harder time learning it if my keybindings are weird. `(add-hook 'magit-mode-hook 'turn-off-evil-mode)`

I'm using this cheatsheet: http://daemianmack.com/magit-cheatsheet.html along with ? for context commands.

Do as you will, evil magit or magit minus evil

**Comment by blak3mill3r** [comment]
Thanks for the response!

I tried loading `evil-magit-rebellion.el` but it didn't work for me. It probably has to do with my use of `use-package` and my lack of understanding.

I did manage to do what I wanted myself, though. It's [here](https://github.com/blak3mill3r/emacs.d/blob/master/evil-magit.el#L4-L13) in case you are curious.

I'm mostly keeping the default magit bindings, except where they conflict with evil-motion's keymap which is what I found most frustrating. I am loving it now that I got it figured out.
